import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { FavoritesProvider } from "@/features/favorites/context/favorites-context";

export const metadata: Metadata = {
  title: "HomeMatch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <FavoritesProvider>
          <Navbar />
          {children}
        </FavoritesProvider>
      </body>
    </html>
  );
}
