import Navbar from "@/components/Navbar";
import { FavoritesProvider } from "@/features/favorites/context/favorites-context";
import { ComparisonProvider } from "@/features/listings/context/comparison-context";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "HomeMatch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <FavoritesProvider>
          <ComparisonProvider>
            <Navbar />
            {children}
          </ComparisonProvider>
        </FavoritesProvider>
      </body>
    </html>
  );
}
