create table listings
(
    id                bigint generated by default as identity
        constraint "Properties_pkey"
            primary key,
    address           text,
    price             numeric(12, 2),
    sqft              integer,
    beds              integer,
    baths             double precision,
    listing_url       text,
    all_photo_urls    text
);