server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
  flyway:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}