server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/homematch_e2e
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
